#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Stopping and removing the systemd service..." --weight=1

ynh_remove_systemd_config

ynh_script_progression --message="Removing logrotate configuration..." --weight=1
ynh_remove_logrotate

ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1
ynh_remove_nginx_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --weight=4

ynh_remove_nodejs

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..."

yunohost service remove $app --log="/var/log/$app/$app.log"

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression --message="Removing various files..." --weight=1

# Remove the log files
ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
