#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Stopping and removing the systemd service..."

ynh_config_remove_systemd

ynh_script_progression "Removing NGINX web server configuration..."
ynh_config_remove_nginx

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

ynh_nodejs_remove

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Removing service in YunoHost..."

yunohost service remove $app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
